plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - prettier-plugin-packagejson
  - prettier-plugin-sh
importOrder:
  - ^[^.]
  - ^[.]
importOrderCaseInsensitive: true
importOrderSortSpecifiers: true
printWidth: 120
